/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.flow.sink

import java.io.File
import java.sql.Timestamp
import java.time.format.DateTimeFormatter
import java.util.TimeZone

import scala.collection.mutable

import org.apache.spark.sql.AnalysisException
import org.apache.spark.sql.flow.{BaseGraphStreamSink, GraphNodeType, SQLFlowGraphEdge, SQLFlowGraphNode, SQLFlowGraphProps}

case class GraphVizMetadataSink(
    imgFormat: String = "svg",
    includeSystemProps: Boolean = false)
  extends GraphFileBatchSink with BaseGraphStreamSink {

  override val filenameSuffix: String = "dot"

  private val cachedNodeColor = "lightblue"

  private val metadataPropKeys = Set(
    SQLFlowGraphProps.ConditionSql,
    SQLFlowGraphProps.ConditionRefs,
    SQLFlowGraphProps.JoinType,
    SQLFlowGraphProps.JoinConditionSql,
    SQLFlowGraphProps.JoinConditionRefs,
    SQLFlowGraphProps.GroupByExpressions,
    SQLFlowGraphProps.PathConditions,
    SQLFlowGraphProps.PathOutputExpressions,
    SQLFlowGraphProps.TargetOutputExpression)

  private val className = {
    getClass.getCanonicalName.replace("$", "")
  }

  override def toGraphString(nodes: Seq[SQLFlowGraphNode], edges: Seq[SQLFlowGraphEdge]): String = {
    if (nodes.nonEmpty) {
      val nodeStrings = nodes.map(generateNodeString)
      val edgeStrings = edges.map(generateEdgeString)
      s"""
         |// Automatically generated by $className
         |digraph {
         |  graph [pad="0.5" nodesep="0.6" ranksep="1.0" fontname="Helvetica" rankdir=LR];
         |  node [shape=plaintext]
         |
         |  ${nodeStrings.sorted.mkString("\n")}
         |  ${edgeStrings.sorted.mkString("\n")}
         |}
       """.stripMargin
    } else {
      ""
    }
  }

  private def filterProps(props: mutable.Map[String, String]): Seq[(String, String)] = {
    props.toSeq.filter { case (key, _) =>
      includeSystemProps ||
        metadataPropKeys.contains(key) ||
        key.startsWith(SQLFlowGraphProps.OutputExpressionByIndexPrefix)
    }.sortBy(_._1)
  }

  private def wrapForHtml(str: String, chunkSize: Int = 80): String = {
    // Escape each chunk independently so we never split an HTML entity like &quot; across lines.
    str.grouped(chunkSize).map(normalizeForHtml).mkString("<br align=\"left\"/>")
  }

  private def normalizeForHtml(str: String): String = {
    str.replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll("\"", "&quot;")
  }

  private def normalizeForDotLabel(str: String): String = {
    str.replace("\\", "\\\\")
      .replace("\"", "\\\"")
      .replace("\n", "\\n")
      .replace("\r", "")
  }

  private def generatePropRows(props: mutable.Map[String, String]): String = {
    filterProps(props).filterNot { case (key, _) =>
      key.startsWith(SQLFlowGraphProps.OutputExpressionByIndexPrefix)
    }.map { case (key, value) =>
      s"""<tr><td align="left"><font point-size="10"><b>${normalizeForHtml(key)}</b>: ${wrapForHtml(value)}</font></td></tr>"""
    }.mkString("\n")
  }

  private def outputExpressionFor(node: SQLFlowGraphNode, idx: Int): Option[String] = {
    node.props.get(s"${SQLFlowGraphProps.OutputExpressionByIndexPrefix}$idx")
  }

  private def generateOutputRows(node: SQLFlowGraphNode): Seq[String] = {
    node.attributeNames.zipWithIndex.map { case (attr, i) =>
      val exprSuffix = outputExpressionFor(node, i).map { expr =>
        s"""<br align="left"/><font point-size="10">expr: ${wrapForHtml(expr)}</font>"""
      }.getOrElse("")
      s"""<tr><td align="left" port="$i">${normalizeForHtml(attr)}$exprSuffix</td></tr>"""
    }
  }

  private def generateNodeString(node: SQLFlowGraphNode): String = {
    node.tpe match {
      case GraphNodeType.TableNode | GraphNodeType.ViewNode | GraphNodeType.QueryNode =>
        generateTableNodeString(node)
      case GraphNodeType.PlanNode | GraphNodeType.LeafPlanNode =>
        generatePlanNodeString(node)
    }
  }

  private def generateEdgeString(edge: SQLFlowGraphEdge): String = {
    val toIdxStr = (i: Option[Int]) => i.map(_.toString).getOrElse("nodeName")
    val propLines = filterProps(edge.props).map { case (key, value) =>
      s"$key: $value"
    }
    val edgeLabel = if (propLines.nonEmpty) {
      val label = normalizeForDotLabel(propLines.mkString("\n"))
      s""" [fontsize="10" label="$label"]"""
    } else {
      ""
    }
    s""""${edge.fromId}":${toIdxStr(edge.fromIdx)} -> "${edge.toId}":${toIdxStr(edge.toIdx)}$edgeLabel;"""
  }

  private def generateTableNodeString(node: SQLFlowGraphNode): String = {
    val nodeColor = if (node.isCached) cachedNodeColor else "black"
    val outputAttrs = generateOutputRows(node)
    val propRows = generatePropRows(node.props)
    val allRows = (outputAttrs ++ Option(propRows).filter(_.nonEmpty)).mkString("\n")
    s"""
       |"${node.uniqueId}" [color="$nodeColor" label=<
       |<table>
       |  <tr><td bgcolor="$nodeColor" port="nodeName"><i><font color="white">${normalizeForHtml(node.ident)}</font></i></td></tr>
       |  $allRows
       |</table>>];
     """.stripMargin
  }

  private def generatePlanNodeString(node: SQLFlowGraphNode): String = {
    val nodeColor = if (node.isCached) cachedNodeColor else "lightgray"
    val outputAttrs = generateOutputRows(node)
    val propRows = generatePropRows(node.props)
    val allRows = (outputAttrs ++ Option(propRows).filter(_.nonEmpty)).mkString("\n")
    s"""
       |"${node.uniqueId}" [label=<
       |<table color="$nodeColor" border="1" cellborder="0" cellspacing="0">
       |  <tr><td bgcolor="$nodeColor" port="nodeName"><i>${normalizeForHtml(node.ident)}</i></td></tr>
       |  $allRows
       |</table>>];
     """.stripMargin
  }

  private def tryGenerateImageFile(options: Map[String, String]): Unit = {
    val dirPath = getOutputDirPathFrom(options)
    val filenamePrefix = getFilenamePrefixFrom(options)
    val dotFile = new File(dirPath, s"$filenamePrefix.$filenameSuffix").getAbsolutePath
    val dstFile = new File(dirPath, s"$filenamePrefix.$imgFormat").getAbsolutePath
    val arguments = s"-T$imgFormat $dotFile > $dstFile"
    SinkUtils.tryToExecuteCommand("dot", arguments)
  }

  override def write(
      nodes: Seq[SQLFlowGraphNode],
      edges: Seq[SQLFlowGraphEdge],
      options: Map[String, String]): Unit = {
    super.write(nodes, edges, options)
    tryGenerateImageFile(options)
  }

  private def getCurrentDateTime(): String = {
    val curTimestamp = new Timestamp(System.currentTimeMillis())
    val zoneId = TimeZone.getTimeZone("UTC").toZoneId
    val formatter = DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS")
    curTimestamp.toLocalDateTime.atZone(zoneId).format(formatter)
  }

  override def append(
      nodes: Seq[SQLFlowGraphNode],
      edges: Seq[SQLFlowGraphEdge],
      options: Map[String, String]): Unit = {
    val rootOutputDir = new File(getOutputDirPathFrom(options))
    if (!rootOutputDir.exists() && !rootOutputDir.mkdir()) {
      throw new AnalysisException("Failed to make root output dir " +
        s"'${rootOutputDir.getAbsolutePath}'")
    }
    val outputDir = new File(rootOutputDir, getCurrentDateTime())
    val writeOptions = {
      val opts = mutable.Map[String, String]()
      opts ++= options
      opts("outputDirPath") = outputDir.getAbsolutePath
      opts.toMap
    }
    super.write(nodes, edges, writeOptions)
    tryGenerateImageFile(writeOptions)
  }
}
